profile:
    dataset: cnc_milling

clean:
    target: X1_ActualPosition
    classification: False
    onehot_encode_target: False
    combine_files: False
    percentage_zeros_threshold: 1.0
    correlation_metric: pearson
    input_max_correlation_threshold: 1.0

featurize:
    # If empty, all input variables are used
    variables_to_include:
        # - variable1
        # - variable2

    # By setting this to True, the add_-options below are overrided.
    use_all_engineered_features_on_all_variables: True

    # List the variables below each add_* to add engineered feature
    add_sum:
        # - variable1
    add_gradient:
        # - variable1
    add_mean:
        # - variable1
    add_maximum:
        # - variable1
    add_minimum:
        # - variable1
    add_min_max_range:
        # - variable1
    add_slope:
        # - variable1
    add_slope_sin:
        # - variable1
    add_slope_cos:
        # - variable1
    add_standard_deviation:
        # - variable1
    add_variance:
        # - variable1
    add_peak_frequency:
        # - variable1
    rolling_window_size_sum: 10
    rolling_window_size_mean: 10
    rolling_window_size_max_min: 10
    rolling_window_size_standard_deviation: 10

    # List features here to remove the raw variables after engineering features
    # from them
    remove_features:
        # - variable1
    target_min_correlation_threshold: 0.0

split:
    train_split: 0.5
    shuffle_files: False
    shuffle_samples_before_split: False

scale:
    input: minmax
    output:

sequentialize:
    window_size: 1
    overlap: 0
    target_size: 1
    shuffle_samples: False
    future_predict: False

train:
    seed: 2020
    learning_method: dt
    ensemble: False
    hyperparameter_tuning: False

    # Parameters for deep learning (dnn, cnn, lstm etc):
    n_epochs: 500
    early_stopping: True
    patience: 20
    activation_function: relu
    batch_size: 256
    n_layers: 2
    n_neurons: [16, 16]
    dropout: 0.1

    # Parameters for cnn and rnn
    n_flattened_layers: 1
    n_flattened_nodes: 16

    # Parameters for cnn:
    kernel_size: 5
    maxpooling: False
    maxpooling_size: 4

    # Parameters for rnn:
    unit_type: LSTM

    # Parameters for transformer:
    ff_dim: 4
    n_transformer_blocks: 4
    n_heads: 4
    head_size: 256

evaluate:
    performance_metric: r2
    threshold_for_ensemble_models: -1000
    dropout_uncertainty_estimation: True
    uncertainty_estimation_sampling_size: 1000
    show_inputs: False

explain: 
    generate_explanations: True
    number_of_background_samples: 10
    number_of_summary_samples: 20
    explanation_method: shap
    seed: 2020
